#!/usr/bin/env groovy

def deployBySSH() {
//    withCredentials([sshUserPrivateKey(credentialsId: 'jenkins.ssh', keyFileVariable: 'identity')]) {
//        remote.identityFile = identity                    
    withCredentials([usernamePassword(credentialsId: 'jenkins.ssh', usernameVariable: 'username', passwordVariable: 'password')]) {
        def SSH_REMOTE = [
            name: 'appinhouse',
            user: 'jenkins-cli',
            host: 'test.server',
            allowAnyHosts: true,
            password: password,
        ]
        def SSH_COMMAND = """cd /srv/appinhouse \
        && docker-compose down \
        && docker-compose pull \
        && docker-compose up -d
        """
        sshCommand remote: SSH_REMOTE, command: SSH_COMMAND
    }
   
}

pipeline {
    agent any
    options {
        skipDefaultCheckout()
        disableConcurrentBuilds()
        buildDiscarder(logRotator(
            daysToKeepStr: '15',
            artifactNumToKeepStr: '20'
        ))
        ansiColor('xterm')
    }
    stages {
        stage('Deploy') {
            steps {
                deployBySSH()
            }
        }
    }
}
